"""shares_maps.py -- SELF-CONTAINED survey-definition metadata for the Shares
Dashboard. Extracted once from the deck (generate_slides.py) on 2026-06-12 so the
data build depends ONLY on the RD Excel, not on any deck file. If the survey answer
options change, regenerate this from the questionnaire / deck."""

IND_LETTER = {'EC': 'E', 'OC': 'O', 'CC': 'C'}

REGION_MAP = {   'West': ['Nordrhein-Westfalen', 'Saarland', 'Rheinland-Pfalz', 'Hessen'],
    'South': ['Bayern', 'Baden-Württemberg'],
    'East': ['Berlin', 'Thüringen', 'Sachsen', 'Brandenburg', 'Sachsen-Anhalt', 'Mecklenburg-Vorpommern'],
    'North': ['Hamburg', 'Schleswig-Holstein', 'Niedersachsen', 'Bremen']}

ALL_SERIES = {   'EC': [   'Dostarlimab + chemotherapy',
              'Durvalumab + chemotherapy +/- Olaparib',
              'Pembrolizumab + chemotherapy',
              'Endocrine Therapy',
              'Dostarlimab',
              'Pembrolizumab',
              'Pembrolizumab + Lenvatinib',
              'Product X',
              'Chemotherapy (carboplatin, taxol)',
              'Clinical Trial',
              'Other'],
    'OC': [   'Bevacizumab + chemotherapy',
              'Mirvetuximab soravtansine',
              'niraparib',
              'Olaparib +/- Bevacizumab',
              'Rucaparib',
              'Product X',
              'Chemotherapy (carboplatin, taxol)',
              'Clinical Trial',
              'Other'],
    'CC': [   'Pembrolizumab +/- Bevacizumab + chemotherapy',
              'Cemiplimab',
              'Tisotumab vedotin',
              'Product X',
              'Chemotherapy (carboplatin, taxol)',
              'Clinical Trial',
              'Other']}

KNOWN_MISSING = {   'IHC3': {'EC': ['Other', 'Product X'], 'OC': ['Other', 'Product X'], 'CC': ['Other', 'Product X']},
    'IHC2': {'EC': ['Other', 'Product X'], 'OC': ['Other', 'Product X'], 'CC': ['Other', 'Product X']},
    'IHCU': {   'EC': ['Other', 'Pembrolizumab', 'Product X'],
                'OC': ['Other', 'Product X'],
                'CC': ['Cemiplimab', 'Clinical Trial', 'Other', 'Product X']},
    'Overall': {'EC': ['Other', 'Product X'], 'OC': ['Other', 'Product X'], 'CC': ['Other', 'Product X']}}

MAPS_IHC3 = {   'EC': {   '1L': {   'Dostarlimab + chemotherapy': 'Q6_10Z_EC_IHC3_1L_A1',
                        'Durvalumab + chemotherapy +/- Olaparib': 'Q6_10Z_EC_IHC3_1L_A2',
                        'Pembrolizumab + chemotherapy': 'Q6_10Z_EC_IHC3_1L_A5',
                        'Endocrine Therapy': 'Q6_10Z_EC_IHC3_1L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC3_1L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC3_1L_A7',
                        'Other': 'Q6_10Z_EC_IHC3_1L_OTH3_1'},
              '2L': {   'Endocrine Therapy': 'Q6_10Z_EC_IHC3_2L_A4',
                        'Dostarlimab': 'Q6_10Z_EC_IHC3_2L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHC3_2L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHC3_2L_A10',
                        'Product X': 'Q6_10Z_EC_IHC3_2L_A11',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC3_2L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC3_2L_A7',
                        'Other': 'Q6_10Z_EC_IHC3_2L_OTH3_2'},
              '3L': {   'Dostarlimab': 'Q6_10Z_EC_IHC3_3L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHC3_3L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHC3_3L_A10',
                        'Product X': 'Q6_10Z_EC_IHC3_3L_A11',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC3_3L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC3_3L_A7',
                        'Other': 'Q6_10Z_EC_IHC3_3L_OTH3_3'}},
    'OC': {   '1L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC3_1L_A1',
                        'niraparib': 'Q6_10Z_OC_IHC3_1L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHC3_1L_A4',
                        'Rucaparib': 'Q6_10Z_OC_IHC3_1L_A5',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC3_1L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC3_1L_A7',
                        'Other': 'Q6_10Z_OC_IHC3_1L_OTH3_1'},
              '2L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC3_2L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHC3_2L_A2',
                        'niraparib': 'Q6_10Z_OC_IHC3_2L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHC3_2L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC3_2L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC3_2L_A7',
                        'Product X': 'Q6_10Z_OC_IHC3_2L_A8',
                        'Other': 'Q6_10Z_OC_IHC3_2L_OTH3_2'},
              '3L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC3_3L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHC3_3L_A2',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC3_3L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC3_3L_A7',
                        'Product X': 'Q6_10Z_OC_IHC3_3L_A8',
                        'Other': 'Q6_10Z_OC_IHC3_3L_OTH3_3'}},
    'CC': {   '1L': {   'Pembrolizumab +/- Bevacizumab + chemotherapy': 'Q6_10Z_CC_IHC3_1L_A1',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC3_1L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC3_1L_A5',
                        'Other': 'Q6_10Z_CC_IHC3_1L_OTH3_1'},
              '2L': {   'Cemiplimab': 'Q6_10Z_CC_IHC3_2L_A2',
                        'Tisotumab vedotin': 'Q6_10Z_CC_IHC3_2L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC3_2L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC3_2L_A5',
                        'Product X': 'Q6_10Z_CC_IHC3_2L_A6',
                        'Other': 'Q6_10Z_CC_IHC3_2L_OTH3_2'},
              '3L': {   'Tisotumab vedotin': 'Q6_10Z_CC_IHC3_3L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC3_3L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC3_3L_A5',
                        'Product X': 'Q6_10Z_CC_IHC3_3L_A6',
                        'Other': 'Q6_10Z_CC_IHC3_3L_OTH3_3'}}}

MAPS_IHC2 = {   'EC': {   '1L': {   'Dostarlimab + chemotherapy': 'Q6_10Z_EC_IHC2_1L_A1',
                        'Durvalumab + chemotherapy +/- Olaparib': 'Q6_10Z_EC_IHC2_1L_A2',
                        'Endocrine Therapy': 'Q6_10Z_EC_IHC2_1L_A4',
                        'Pembrolizumab + chemotherapy': 'Q6_10Z_EC_IHC2_1L_A5',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC2_1L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC2_1L_A7',
                        'Other': 'Q6_10Z_EC_IHC2_1L_OTH2_1'},
              '2L': {   'Endocrine Therapy': 'Q6_10Z_EC_IHC2_2L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC2_2L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC2_2L_A7',
                        'Dostarlimab': 'Q6_10Z_EC_IHC2_2L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHC2_2L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHC2_2L_A10',
                        'Product X': 'Q6_10Z_EC_IHC2_2L_A11',
                        'Other': 'Q6_10Z_EC_IHC2_2L_OTH2_2'},
              '3L': {   'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHC2_3L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHC2_3L_A7',
                        'Dostarlimab': 'Q6_10Z_EC_IHC2_3L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHC2_3L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHC2_3L_A10',
                        'Product X': 'Q6_10Z_EC_IHC2_3L_A11',
                        'Other': 'Q6_10Z_EC_IHC2_3L_OTH2_3'}},
    'OC': {   '1L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC2_1L_A1',
                        'niraparib': 'Q6_10Z_OC_IHC2_1L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHC2_1L_A4',
                        'Rucaparib': 'Q6_10Z_OC_IHC2_1L_A5',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC2_1L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC2_1L_A7',
                        'Other': 'Q6_10Z_OC_IHC2_1L_OTH2_1'},
              '2L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC2_2L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHC2_2L_A2',
                        'niraparib': 'Q6_10Z_OC_IHC2_2L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHC2_2L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC2_2L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC2_2L_A7',
                        'Product X': 'Q6_10Z_OC_IHC2_2L_A8',
                        'Other': 'Q6_10Z_OC_IHC2_2L_OTH2_2'},
              '3L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHC2_3L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHC2_3L_A2',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHC2_3L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHC2_3L_A7',
                        'Product X': 'Q6_10Z_OC_IHC2_3L_A8',
                        'Other': 'Q6_10Z_OC_IHC2_3L_OTH2_3'}},
    'CC': {   '1L': {   'Pembrolizumab +/- Bevacizumab + chemotherapy': 'Q6_10Z_CC_IHC2_1L_A1',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC2_1L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC2_1L_A5',
                        'Other': 'Q6_10Z_CC_IHC2_1L_OTH2_1'},
              '2L': {   'Cemiplimab': 'Q6_10Z_CC_IHC2_2L_A2',
                        'Tisotumab vedotin': 'Q6_10Z_CC_IHC2_2L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC2_2L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC2_2L_A5',
                        'Product X': 'Q6_10Z_CC_IHC2_2L_A6',
                        'Other': 'Q6_10Z_CC_IHC2_2L_OTH2_2'},
              '3L': {   'Tisotumab vedotin': 'Q6_10Z_CC_IHC2_3L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHC2_3L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHC2_3L_A5',
                        'Product X': 'Q6_10Z_CC_IHC2_3L_A6',
                        'Other': 'Q6_10Z_CC_IHC2_3L_OTH2_3'}}}

MAPS_IHCU = {   'EC': {   '1L': {   'Dostarlimab + chemotherapy': 'Q6_10Z_EC_IHCU_1L_A1',
                        'Durvalumab + chemotherapy +/- Olaparib': 'Q6_10Z_EC_IHCU_1L_A2',
                        'Endocrine Therapy': 'Q6_10Z_EC_IHCU_1L_A4',
                        'Pembrolizumab + chemotherapy': 'Q6_10Z_EC_IHCU_1L_A5',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHCU_1L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHCU_1L_A7',
                        'Other': 'Q6_10Z_EC_IHCU_1L_OTHU_1'},
              '2L': {   'Endocrine Therapy': 'Q6_10Z_EC_IHCU_2L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHCU_2L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHCU_2L_A7',
                        'Dostarlimab': 'Q6_10Z_EC_IHCU_2L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHCU_2L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHCU_2L_A10',
                        'Product X': 'Q6_10Z_EC_IHCU_2L_A11',
                        'Other': 'Q6_10Z_EC_IHCU_2L_OTHU_2'},
              '3L': {   'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_EC_IHCU_3L_A6',
                        'Clinical Trial': 'Q6_10Z_EC_IHCU_3L_A7',
                        'Dostarlimab': 'Q6_10Z_EC_IHCU_3L_A8',
                        'Pembrolizumab': 'Q6_10Z_EC_IHCU_3L_A9',
                        'Pembrolizumab + Lenvatinib': 'Q6_10Z_EC_IHCU_3L_A10',
                        'Product X': 'Q6_10Z_EC_IHCU_3L_A11',
                        'Other': 'Q6_10Z_EC_IHCU_3L_OTHU_3'}},
    'OC': {   '1L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHCU_1L_A1',
                        'niraparib': 'Q6_10Z_OC_IHCU_1L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHCU_1L_A4',
                        'Rucaparib': 'Q6_10Z_OC_IHCU_1L_A5',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHCU_1L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHCU_1L_A7',
                        'Other': 'Q6_10Z_OC_IHCU_1L_OTHU_1'},
              '2L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHCU_2L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHCU_2L_A2',
                        'niraparib': 'Q6_10Z_OC_IHCU_2L_A3',
                        'Olaparib +/- Bevacizumab': 'Q6_10Z_OC_IHCU_2L_A4',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHCU_2L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHCU_2L_A7',
                        'Product X': 'Q6_10Z_OC_IHCU_2L_A8',
                        'Other': 'Q6_10Z_OC_IHCU_2L_OTHU_2'},
              '3L': {   'Bevacizumab + chemotherapy': 'Q6_10Z_OC_IHCU_3L_A1',
                        'Mirvetuximab soravtansine': 'Q6_10Z_OC_IHCU_3L_A2',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_OC_IHCU_3L_A6',
                        'Clinical Trial': 'Q6_10Z_OC_IHCU_3L_A7',
                        'Product X': 'Q6_10Z_OC_IHCU_3L_A8',
                        'Other': 'Q6_10Z_OC_IHCU_3L_OTHU_3'}},
    'CC': {   '1L': {   'Pembrolizumab +/- Bevacizumab + chemotherapy': 'Q6_10Z_CC_IHCU_1L_A1',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHCU_1L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHCU_1L_A5',
                        'Other': 'Q6_10Z_CC_IHCU_1L_OTHU_1'},
              '2L': {   'Cemiplimab': 'Q6_10Z_CC_IHCU_2L_A2',
                        'Tisotumab vedotin': 'Q6_10Z_CC_IHCU_2L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHCU_2L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHCU_2L_A5',
                        'Product X': 'Q6_10Z_CC_IHCU_2L_A6',
                        'Other': 'Q6_10Z_CC_IHCU_2L_OTHU_2'},
              '3L': {   'Tisotumab vedotin': 'Q6_10Z_CC_IHCU_3L_A3',
                        'Chemotherapy (carboplatin, taxol)': 'Q6_10Z_CC_IHCU_3L_A4',
                        'Clinical Trial': 'Q6_10Z_CC_IHCU_3L_A5',
                        'Product X': 'Q6_10Z_CC_IHCU_3L_A6',
                        'Other': 'Q6_10Z_CC_IHCU_3L_OTHU_3'}}}

# Series stack/legend order as it appears in the deck charts (slides 11-18), extracted
# once from the template chart XML on 2026-06-12. First entry = bottom of the stack /
# first in legend, matching PowerPoint. Names use the ALL_SERIES canonical spelling.
# Data series absent from the deck chart (e.g. EC "Pembrolizumab", "Other") are appended
# after these, in ALL_SERIES order, by ordered_series().
SERIES_ORDER = {
    "EC": ["Product X", "Pembrolizumab + Lenvatinib", "Pembrolizumab + chemotherapy",
           "Durvalumab + chemotherapy +/- Olaparib", "Dostarlimab + chemotherapy",
           "Dostarlimab", "Endocrine Therapy", "Clinical Trial",
           "Chemotherapy (carboplatin, taxol)"],
    "OC": ["Product X", "Rucaparib", "niraparib", "Mirvetuximab soravtansine",
           "Bevacizumab + chemotherapy", "Olaparib +/- Bevacizumab",
           "Chemotherapy (carboplatin, taxol)", "Clinical Trial"],
    "CC": ["Product X", "Pembrolizumab +/- Bevacizumab + chemotherapy", "Cemiplimab",
           "Tisotumab vedotin", "Clinical Trial", "Chemotherapy (carboplatin, taxol)"],
}


def ordered_series(ind):
    """Deck chart order first, then any remaining ALL_SERIES entries (deck-absent)."""
    al = ALL_SERIES[ind]
    deck = [s for s in SERIES_ORDER.get(ind, []) if s in al]
    return deck + [s for s in al if s not in deck]


def map_region(v):
    if not v: return "Unknown"
    s=str(v)
    for region, states in REGION_MAP.items():
        if any(st in s for st in states): return region
    return "Other"
